### ISSUE TITLE
missing "

### ISSUE THREAD

**Issue by JHincks** [Obarun/obarun-install-themes#2]
Hi Eric,
i believe in "obarun-install-themes/jwm/rootfs/etc/skel/.config/jwm/tray" you have a " missing in line 4

width=-1"

should be

width="-1"

...i guess.

This is my first bug-report ever! I hope it wasn't dumb. ;)

**Comment by Obarun** [comment]
good catch, thanks
fixed 095b36a3e1f1e45c555bf3cc3e43fc5cca1ff4db
