### ISSUE TITLE
Xfce theme cannot be used: gnome-themes-standard package is not found.

### ISSUE THREAD

**Issue by FredBezies** [Obarun/obarun-install-themes#3]
A really simple bug to reproduce.

After updating both obarun and obarun-install-themes, xfce was not installed. Looks like there is a mistake in xfce config file...

Just look at the screenshot...

![virtualbox_obarun 2018 06_25_05_2018_17_23_17](https://user-images.githubusercontent.com/8571419/40552700-c28ea006-6040-11e8-9eeb-068b0d19ab4e.png)

**Comment by FredBezies** [comment]
I removed the last line from /var/lib/obarun/obarun-install/config/xfce4/package_list/desktop in /var/and installation worked near good...

**Comment by Obarun** [comment]
thanks for the report, fixed by the same commit as #5
