### ISSUE TITLE
Plasma / Xfce installation process is broken while trying to launch xdg-user-dirs-update.

### ISSUE THREAD

**Issue by FredBezies** [Obarun/obarun-install-themes#4]
After fixing bug for broken list theme, bug #3 , I faced another bug, related to xdg-user-dirs-update!

See attached screenshot...

![virtualbox_obarun 2018 06_25_05_2018_17_44_04](https://user-images.githubusercontent.com/8571419/40553528-3c0bf418-6043-11e8-806c-53955b08f8c7.png)

Ouch! Please, don't call me bugman!

Looks like xdg-user-dirs is missing in theme files...

**Comment by Obarun** [comment]
Thanks for the report, fixed by on the same commit as #5
