### ISSUE TITLE
Xfce theme: please add gvfs to install theme

### ISSUE THREAD

**Issue by FredBezies** [Obarun/obarun-install-themes#5]
Without it, you cannot get trash icon on the desktop and you cannot manage USB keys.

After adding gvfs in post install, I got a better working xfce.

![virtualbox_obarun 2018 06_25_05_2018_17_50_40](https://user-images.githubusercontent.com/8571419/40553842-2bf8c2a8-6044-11e8-9387-94eaa52dd57c.png)

**Comment by Obarun** [comment]
Thanks for the report, this was rectified https://github.com/Obarun/obarun-install-themes/commit/4f34c6ff401e52948a24cc178f3fa2b358620305
